// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArXwmjmoLbLN6HRL96eEQbCNjTCkj9NwA',
    appId: '1:764590432915:web:02ca7e64187eac79d4e366',
    messagingSenderId: '764590432915',
    projectId: 'kawal-sawit',
    authDomain: 'kawal-sawit.firebaseapp.com',
    storageBucket: 'kawal-sawit.appspot.com',
    measurementId: 'G-P349TMBR81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5iSQEz39tJZS9Xjixkfc3FWngU43F600',
    appId: '1:764590432915:android:a2c773594653a700d4e366',
    messagingSenderId: '764590432915',
    projectId: 'kawal-sawit',
    storageBucket: 'kawal-sawit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAjeWgONILCJhJMKFRsfht2QPnM2H_6Lw',
    appId: '1:764590432915:ios:d0cae599a8832a6fd4e366',
    messagingSenderId: '764590432915',
    projectId: 'kawal-sawit',
    storageBucket: 'kawal-sawit.appspot.com',
    iosBundleId: 'com.example.kawalSawit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAjeWgONILCJhJMKFRsfht2QPnM2H_6Lw',
    appId: '1:764590432915:ios:d0cae599a8832a6fd4e366',
    messagingSenderId: '764590432915',
    projectId: 'kawal-sawit',
    storageBucket: 'kawal-sawit.appspot.com',
    iosBundleId: 'com.example.kawalSawit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArXwmjmoLbLN6HRL96eEQbCNjTCkj9NwA',
    appId: '1:764590432915:web:36b9078a83e4e6f4d4e366',
    messagingSenderId: '764590432915',
    projectId: 'kawal-sawit',
    authDomain: 'kawal-sawit.firebaseapp.com',
    storageBucket: 'kawal-sawit.appspot.com',
    measurementId: 'G-EX92LM5SN2',
  );
}
